FROM ros:humble-ros-base

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    vim \
    curl \
    wget \
    build-essential \
    python3-colcon-common-extensions \
    python3-pip \
    ros-humble-ros2cli \
    ros-humble-rqt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc && \
    echo "source /workspaces/code/install/setup.bash" >> /root/.bashrc

WORKDIR /workspaces/code
RUN chmod 777 /workspaces/code


CMD ["/bin/bash"]